// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClusterInput 是 AddCluster 的前端入参。Token 只进 Keychain，绝不落盘。
 */
export class ClusterInput {
    "id": string;
    "name": string;
    "address": string;
    "region": string;
    "namespace": string;
    "tls": boolean;
    "insecureSkipVerify"?: boolean;

    /**
     * 可选：留空则沿用 Keychain 已有 token
     */
    "token": string;

    /**
     * UseEnvToken：为 true 且 Token 为空时，用 NOMAD_TOKEN（不经前端明文往返）。
     */
    "useEnvToken"?: boolean;

    /** Creates a new ClusterInput instance. */
    constructor($$source: Partial<ClusterInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("tls" in $$source)) {
            this["tls"] = false;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterInput($$parsedSource as Partial<ClusterInput>);
    }
}

/**
 * SettingsInput 是 UpdateSettings 的前端入参（与 config.AppSettings 同构，
 * 单独定义避免前端直接依赖 config 包路径变更）。
 */
export class SettingsInput {
    "confirmDestructive": boolean;
    "autoRestoreActive": boolean;
    "healthIntervalSec": number;
    "metricsIntervalSec": number;
    "defaultRegion": string;
    "defaultNamespace": string;

    /** Creates a new SettingsInput instance. */
    constructor($$source: Partial<SettingsInput> = {}) {
        if (!("confirmDestructive" in $$source)) {
            this["confirmDestructive"] = false;
        }
        if (!("autoRestoreActive" in $$source)) {
            this["autoRestoreActive"] = false;
        }
        if (!("healthIntervalSec" in $$source)) {
            this["healthIntervalSec"] = 0;
        }
        if (!("metricsIntervalSec" in $$source)) {
            this["metricsIntervalSec"] = 0;
        }
        if (!("defaultRegion" in $$source)) {
            this["defaultRegion"] = "";
        }
        if (!("defaultNamespace" in $$source)) {
            this["defaultNamespace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput($$parsedSource as Partial<SettingsInput>);
    }
}
