// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// Wails v3 beta.3 workaround: generator emits "main.App.*" IDs for package
// main while the runtime hashes the real module path, so the generated
// wails_obfuscated build tag was stripped to keep binding IDs stable in
// plain builds. Re-run `wails3 generate bindings -obfuscated ./...` and
// strip the tag again if this file is regenerated.

package main

import (
	"github.com/wailsapp/wails/v3/pkg/application"
)

func init() {
	application.RegisterBindingMethodID((*App).AddCluster, 1297766566)
	application.RegisterBindingMethodID((*App).EvaluateJob, 3390403861)
	application.RegisterBindingMethodID((*App).GetAllocLoad, 1987670824)
	application.RegisterBindingMethodID((*App).GetClusterLoad, 2457669303)
	application.RegisterBindingMethodID((*App).GetJob, 2134918486)
	application.RegisterBindingMethodID((*App).GetNodeLoads, 3098263772)
	application.RegisterBindingMethodID((*App).ListClusters, 2689603438)
	application.RegisterBindingMethodID((*App).ListJobAllocations, 2916105591)
	application.RegisterBindingMethodID((*App).ListJobs, 4257729417)
	application.RegisterBindingMethodID((*App).ListNodes, 3103789542)
	application.RegisterBindingMethodID((*App).RemoveCluster, 624040237)
	application.RegisterBindingMethodID((*App).RestartAlloc, 78022057)
	application.RegisterBindingMethodID((*App).RunJob, 3247404837)
	application.RegisterBindingMethodID((*App).ScaleJob, 1691104880)
	application.RegisterBindingMethodID((*App).SetActiveCluster, 4053701917)
	application.RegisterBindingMethodID((*App).StopAlloc, 455674126)
	application.RegisterBindingMethodID((*App).StopJob, 1508425892)
	application.RegisterBindingMethodID((*App).TestConnection, 1257240193)
	application.RegisterBindingMethodID((*App).TestConnectionInput, 782476599)
	application.RegisterBindingMethodID((*App).UpdateCluster, 520897430)
}
